from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from psycopg.types.json import Jsonb

from .auth import session_from_request
from .db import connection
from .utils import as_dict

AUDIT_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS public.smg_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,
  entity_id text NOT NULL DEFAULT '',
  action text NOT NULL,
  actor text NOT NULL DEFAULT 'server',
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS smg_audit_log_entity_idx
  ON public.smg_audit_log(entity_type, entity_id, created_at DESC);
ALTER TABLE public.smg_audit_log ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.smg_backup_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('daily','monthly')),
  period_key text NOT NULL,
  source text NOT NULL DEFAULT 'python-fastapi',
  client_id text NOT NULL DEFAULT '',
  snapshot jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(kind, period_key)
);
ALTER TABLE public.smg_backup_revisions ENABLE ROW LEVEL SECURITY;
"""

_schema_ready = False


async def ensure_audit_schema() -> None:
    global _schema_ready
    if _schema_ready:
        return
    async with connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(AUDIT_SCHEMA_SQL)
    _schema_ready = True


async def record_audit(
    request,
    entity_type: str,
    action: str,
    *,
    entity_id: str = "",
    details: dict | None = None,
) -> None:
    await ensure_audit_schema()
    session = await session_from_request(request) if request is not None else None
    actor = str((session or {}).get("sub") or "server")
    safe_details = {
        key: value
        for key, value in as_dict(details).items()
        if key.lower() not in {"password", "token", "synckey", "authorization"}
    }
    async with connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                INSERT INTO public.smg_audit_log(entity_type,entity_id,action,actor,details,created_at)
                VALUES (%s,%s,%s,%s,%s,now())
                """,
                (
                    str(entity_type)[:80],
                    str(entity_id)[:160],
                    str(action)[:80],
                    actor[:160],
                    Jsonb(safe_details),
                ),
            )


async def capture_backup(snapshot: dict, *, source: str, client_id: str = "") -> None:
    """Keep one immutable daily and monthly pre-change snapshot in the database."""
    await ensure_audit_schema()
    now = datetime.now(timezone.utc)
    periods = (("daily", now.strftime("%Y-%m-%d")), ("monthly", now.strftime("%Y-%m")))
    async with connection() as conn:
        async with conn.cursor() as cur:
            for kind, period in periods:
                await cur.execute(
                    """
                    INSERT INTO public.smg_backup_revisions(kind,period_key,source,client_id,snapshot,created_at)
                    VALUES (%s,%s,%s,%s,%s,now())
                    ON CONFLICT (kind,period_key) DO NOTHING
                    """,
                    (
                        kind,
                        period,
                        str(source or "python-fastapi")[:120],
                        str(client_id or "")[:160],
                        Jsonb(snapshot),
                    ),
                )
