-- Base de schema: aplique somente no novo projeto Supabase após revisão.
-- Additive only: no production rows are changed or removed.
CREATE TABLE IF NOT EXISTS public.smg_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,
  entity_id text NOT NULL DEFAULT '',
  action text NOT NULL,
  actor text NOT NULL DEFAULT 'server',
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS smg_audit_log_entity_idx ON public.smg_audit_log(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS smg_audit_log_actor_created_idx ON public.smg_audit_log(actor, created_at DESC);
ALTER TABLE public.smg_audit_log ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.smg_backup_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('daily','monthly')),
  period_key text NOT NULL,
  source text NOT NULL DEFAULT 'python-fastapi',
  client_id text NOT NULL DEFAULT '',
  snapshot jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(kind, period_key)
);
CREATE INDEX IF NOT EXISTS smg_backup_revisions_created_idx ON public.smg_backup_revisions(created_at DESC);
ALTER TABLE public.smg_backup_revisions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.smg_rate_limits (
  bucket_key text PRIMARY KEY,
  hit_count integer NOT NULL DEFAULT 0 CHECK (hit_count >= 0),
  reset_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS smg_rate_limits_reset_idx ON public.smg_rate_limits(reset_at);
ALTER TABLE public.smg_rate_limits ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.smg_audit_log IS 'Trilha interna imutável de ações administrativas do backend Python.';
COMMENT ON TABLE public.smg_backup_revisions IS 'Snapshots diários e mensais anteriores a sincronizações destrutivas.';
COMMENT ON TABLE public.smg_rate_limits IS 'Contadores persistentes para proteção de login e formulários em ambiente serverless.';
